name: oluko_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+256

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.2.1
  stop_watch_timer: ^1.3.0
  http: ^0.13.3
  flutter_overlay_loader: ^0.1.1
  shared_preferences: ^2.0.8
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.8
  in_app_purchase: ^3.1.0
  google_sign_in: ^5.1.1
  firebase_auth: ^3.3.7
  flutter_facebook_auth: ^3.5.7
  flutter_bloc: ^8.0.0
  timeago: ^3.0.2
  flutter_dotenv: ^3.1.0
  transparent_image: ^2.0.0
  firebase_storage: ^10.2.7
  # flutter_ffmpeg: ^0.4.0
  filesize: ^2.0.1
  path_provider: ^2.0.9
  flutter_colorpicker: ^0.6.0
  webview_flutter: ^0.3.24
  amazon_cognito_identity_dart_2: ^1.0.3
  chewie: ^1.2.2
  flutter_slidable: ^0.6.0
  # Use with the CupertinoIcons class for iOS style icons.
  camera: 0.8.1+1
  cupertino_icons: ^1.0.3
  global_configuration: ^2.0.0-nullsafety.1
  intl: ^0.17.0
  enum_to_string: ^2.0.1
  percent_indicator: "^2.1.5"
  # simple_timer: ^2.0.0
  # audioplayers: ^0.18.0
  # sound_mode: ^1.0.2
  # numberpicker: ^2.1.1
  flutter_localizations:
    sdk: flutter
  image: ^3.0.2
  drag_and_drop_gridview: ^1.0.8
  sentry_flutter: ^5.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_image_compress: ^1.1.0
  nil: ^1.1.1
  permission_handler: ^9.2.0
  firebase_database: ^9.0.6
  timeline_tile: ^2.0.0
  badges: ^2.0.1
  syncfusion_flutter_gauges: 19.4.48
  audioplayers: ^0.20.1
  uuid: ^3.0.5
  flutter_sound_lite: ^8.3.9
  equatable: ^2.0.3
  wakelock: ^0.6.1+1
  flutter_neumorphic: ^3.2.0
  numberpicker: ^2.1.1
  step_progress_indicator: ^1.0.2
  avatar_glow: ^2.0.2
  sliver_tools: ^0.2.5
  video_thumbnail: ^0.4.6
  photo_manager: ^1.3.10
  dio: ^4.0.4
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  visibility_detector: ^0.2.2
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.3.0
  native_device_orientation: ^1.1.2
  the_apple_sign_in: ^1.1.1
  jwt_decoder: ^2.0.1
  url_launcher: ^6.1.5
  sound_mode: ^2.0.2
  headset_connection_event: ^2.1.1
  video_player: ^2.4.9
  image_picker: ^0.8.6
  cached_network_image: ^3.2.0
  readmore: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  image_test_utils: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0
  lint: ^1.0.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1 
  provider: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  # flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/assessment/
    - assets/courses/
    - assets/login/
    - assets/profile/
    - assets/lang/
    - assets/self_recording/
    - assets/bottom_navigation_bar/
    - assets/home/
    - assets/icon/
    - assets/neumorphic/
    - assets/fonts/
    - assets/collage_people/
    - assets/collage_logos/
    - assets/sounds/
    - assets/utils/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
